### ISSUE TITLE
classified type

### ISSUE THREAD

**Issue by dannypsnl** [dannypsnl/violet#105]
This is a super early name, the point of this is distinguish type to different part, I guess related to modal logic.

Motivation example #108 
```lean
def f(): A
  requires R1
  requires R2
  requires ...
  ensures P1
  ensures P2
  ensures ...
=> ...
```

The idea is let `f` has type `{R1 R2 ... : Prop} -> Σ (r : A), P1 x P2 x ...`, this is because some proof is easy if we do it with definition, especially some algorithm sub-program.

The came up problem is, the type `P1 x P2 x ...` is irrelevant in runtime, so drop them is a good idea.

To archive that, we want to say `Prop` is a **proof type**, it has no usage in runtime, such type can be dropped in **runtime type**. The explanation is complicated, and I haven't check theory problem, so let's see an example to get the point:

$$
\frac{
  \Gamma \vdash P : Prop, T : Type
}{
  \Gamma \vdash IO (T \times P) = IO \\ T
}
$$

**Comment by LemonHX** [comment]
you have mentioned splitting impls and def, how about spliting requires ensures to headers?

```
-- headers
requirement f(): A
  requires R1
  ensure P1
```
and in impl
```
def f() : A :=
  -- ...
``

**Comment by dannypsnl** [comment]
It sounds interesting, let me think about it tomorrow

**Comment by dannypsnl** [comment]
I agree with you, considering the case that B using A, and B only imports A’s signature file.

This setup can both allows B’s related lemmas check without requiring A’s implementation, and B also can write assumptions without A’s implementation too. Then B and A get independent compiling

**Comment by dannypsnl** [comment]
Notice that signature will require implementation prove these requirements, and hence, the code are still safe

**Comment by dannypsnl** [comment]
moved
