### ISSUE TITLE
define record syntax

### ISSUE THREAD

**Issue by dannypsnl** [dannypsnl/violet#106]
Of course we already have an implementation, but that's not the syntax we want to have, so this issue defines the result should be:

### Result
```lean
record A where
  f : T
  f2 : T2
  -- ...
```
### Current
```lean
record A {
  f : T,
  f2 : T2,
  -- ...
}
```

**Comment by LemonHX** [comment]
how about allowing both by
```
def A : Type := record {
  f : T,
  f2 : T2,
  -- ...
}
 ```
 
 and
 ```
 record A where
 -- ...
 ```
 is just a syntax sugar?

**Comment by dannypsnl** [comment]
Yes, it's just a syntax sugar, so the first form will not quite help? We should not consider it as a value
